[package]
name = "vkvk_generator"
description = "Parser and code generator for vk.xml"
repository = "https://github.com/Lokathor/vkvk"
version = "0.0.0"
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"

publish = false

[dependencies]
convert_case = "0.6.0"
magnesium = "1.2"
