[package]
name = "vkvk_generator"
description = "Parser and code generator for vk.xml"
repository = "https://github.com/Lokathor/vkvk"
version = "0.1.0+vk1.3.241"
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"

[dependencies]
magnesium = "1.2"
