[package]
name = "vkvk"
description = "A vulkan library."
repository = "https://github.com/Lokathor/vkvk"
version = "0.1.0+vk1.3.241"
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"

[dependencies]
bitfrob = "1.0.0"

[dev-dependencies]
beryllium = "0.9.2"
magnesium = "1.2"

[profile.dev]
opt-level = 1
