/// Khronos: [VkColorSpaceKHR](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkColorSpaceKHR.html)
#[derive(Clone, Copy, Default, PartialEq, Eq)]
#[repr(transparent)]
pub struct VkColorSpaceKHR(u32);
impl core::fmt::Debug for VkColorSpaceKHR {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    match *self {
      VK_COLOR_SPACE_SRGB_NONLINEAR_KHR => write!(f, "VK_COLOR_SPACE_SRGB_NONLINEAR_KHR"),
      VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT => {
        write!(f, "VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT")
      }
      VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT => {
        write!(f, "VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT")
      }
      VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT => write!(f, "VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT"),
      VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT => write!(f, "VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT"),
      VK_COLOR_SPACE_BT709_LINEAR_EXT => write!(f, "VK_COLOR_SPACE_BT709_LINEAR_EXT"),
      VK_COLOR_SPACE_BT709_NONLINEAR_EXT => write!(f, "VK_COLOR_SPACE_BT709_NONLINEAR_EXT"),
      VK_COLOR_SPACE_BT2020_LINEAR_EXT => write!(f, "VK_COLOR_SPACE_BT2020_LINEAR_EXT"),
      VK_COLOR_SPACE_HDR10_ST2084_EXT => write!(f, "VK_COLOR_SPACE_HDR10_ST2084_EXT"),
      VK_COLOR_SPACE_DOLBYVISION_EXT => write!(f, "VK_COLOR_SPACE_DOLBYVISION_EXT"),
      VK_COLOR_SPACE_HDR10_HLG_EXT => write!(f, "VK_COLOR_SPACE_HDR10_HLG_EXT"),
      VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT => write!(f, "VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT"),
      VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT => write!(f, "VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT"),
      VK_COLOR_SPACE_PASS_THROUGH_EXT => write!(f, "VK_COLOR_SPACE_PASS_THROUGH_EXT"),
      VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT => {
        write!(f, "VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT")
      }
      VK_COLOR_SPACE_DISPLAY_NATIVE_AMD => write!(f, "VK_COLOR_SPACE_DISPLAY_NATIVE_AMD"),
      other => write!(f, "VkColorSpaceKHR({})", other.0),
    }
  }
}
pub const VK_COLOR_SPACE_SRGB_NONLINEAR_KHR: VkColorSpaceKHR = VkColorSpaceKHR(0);
pub const VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT: VkColorSpaceKHR = VkColorSpaceKHR(1000104001);
pub const VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT: VkColorSpaceKHR = VkColorSpaceKHR(1000104002);
pub const VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT: VkColorSpaceKHR = VkColorSpaceKHR(1000104003);
pub const VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT: VkColorSpaceKHR = VkColorSpaceKHR(1000104004);
pub const VK_COLOR_SPACE_BT709_LINEAR_EXT: VkColorSpaceKHR = VkColorSpaceKHR(1000104005);
pub const VK_COLOR_SPACE_BT709_NONLINEAR_EXT: VkColorSpaceKHR = VkColorSpaceKHR(1000104006);
pub const VK_COLOR_SPACE_BT2020_LINEAR_EXT: VkColorSpaceKHR = VkColorSpaceKHR(1000104007);
pub const VK_COLOR_SPACE_HDR10_ST2084_EXT: VkColorSpaceKHR = VkColorSpaceKHR(1000104008);
pub const VK_COLOR_SPACE_DOLBYVISION_EXT: VkColorSpaceKHR = VkColorSpaceKHR(1000104009);
pub const VK_COLOR_SPACE_HDR10_HLG_EXT: VkColorSpaceKHR = VkColorSpaceKHR(1000104010);
pub const VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT: VkColorSpaceKHR = VkColorSpaceKHR(1000104011);
pub const VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT: VkColorSpaceKHR = VkColorSpaceKHR(1000104012);
pub const VK_COLOR_SPACE_PASS_THROUGH_EXT: VkColorSpaceKHR = VkColorSpaceKHR(1000104013);
pub const VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT: VkColorSpaceKHR = VkColorSpaceKHR(1000104014);
pub const VK_COLOR_SPACE_DISPLAY_NATIVE_AMD: VkColorSpaceKHR = VkColorSpaceKHR(1000213000);
